version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: tmrw_local_django
    container_name: tmrw_local_django
    platform: linux/arm64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:14.3-alpine
    container_name: tmrw_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - .envs/.local
