# Generated by Django 3.2.16 on 2023-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
